### ISSUE TITLE
Orientation Issue

### ISSUE THREAD

**Issue by Kuladeepjayker** [ericwaetke/Vue-Sparkles#4]
It won't work properly. When I use this package if is affecting my other components and it's turning content 180 degrees.

**Comment by ericwaetke** [comment]
This should have been solved with #3, but I guess the package itself isn't updated yet. I'll get on that asap

**Comment by ericwaetke** [comment]
Fixed with previously mentioned PR and release version 1.1.0

**Comment by Kuladeepjayker** [comment]
Thank you for support...

**Comment by ericwaetke** [comment]
no problem :)
